project:
  type: book
  output-dir: docs

book:
  title: "Portofolio M. Abizzar G."
  subtitle: "Seorang mahasiswa naif yang berusaha menjadi yang terbaik"
  author: "13523155 - M. Abizzar Gamadrian"
  date: "10/21/2025"
  chapters:
    - index.qmd
    - All_About_me/index.qmd
    - My_Song_for_You/index.qmd
    - My_Stories_for_You/index.qmd
    - My_Shapes/index.qmd
    - My_Personal_Reviews/index.qmd
    - My_Concepts/index.qmd
    - My_Opinions/index.qmd
    - My_Innovations/index.qmd
    - My_Knowledge/index.qmd
    - My_Professional_Reviews/index.qmd
    - summary.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme:
      - cosmo
      - brand
  pdf:
    documentclass: scrreprt



